# Generated by Django 3.1.8 on 2022-03-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loggedIn',
            field=models.BooleanField(default=False),
        ),
    ]
