# Generated by Django 3.2 on 2022-04-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vedios',
            new_name='Video',
        ),
    ]
