# Generated by Django 3.2 on 2022-04-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_rename_vedios_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='couseName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
